on:
    push:
      branches: ["main"]
  
jobs:
    fe-build:
      name: Build source code to Docker image
      runs-on: ubuntu-22.04 
      steps:
        - name: Checkout Develop
          uses: actions/checkout@v3
  
        - name: DockerHub Login
          uses: docker/login-action@v3.1.0
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_TOKEN}}
  
        - name: Build Image And Push
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ${{secrets.DOCKER_USERNAME}}/pimtool-client:latest
    
    staging-fe-deploy:
      name: Deploy Staging FE Admin To Google Service Server For Testing
      runs-on: arisa-server
      needs: fe-build
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
      - name: DockerHub Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Stop PIM Client
        run: docker compose -p pimtool-application down pimtool-client --rmi all -v
      - name: Deploy Client
        run: docker compose -p pimtool-application up -d pimtool-client